### ISSUE TITLE
구매. 허먼밀러 의자

### ISSUE THREAD

**Issue by lionkang** [muraYlion/FelizLaVida#273]
회사 공동구매 진행
<img width="1286" alt="PowerPoint_프레젠테이션" src="https://user-images.githubusercontent.com/1281434/82397303-20399e00-9a8b-11ea-92ce-254601ce121d.png">

**Comment by lionkang** [comment]
안녕하세요.  구매요쳥드립니다.
허먼밀러 + Headrest 1set 입니다.


구매자
- 강수형, 금융플랫폼, 사원

배송지
- 강수형, 01공-22삼9-1오09
- 서울 성동구 금호산8길 13 금호자이2차 103동 x01호

확인 부탁드리겠습니다. 
감사합니다.

**Comment by lionkang** [comment]
안녕하세요  강수형 님,

가림 허먼 밀러 강정민 입니다.


 

Herman Miller 사의 New Aeron Chair에 관심을 가져주셔서 감사합니다.

메일로 보내주신 주문서 확인하였습니다.


 

제품 발송은 입금 순서대로 6월 2일 이후 발송 될 예정입니다.

1차 발주 수량보다 많은 임직원 분들이 문의를 주신 상황입니다.

2차 발주 품들은7월 중순에서 말에 입고 될 예정입니다. 이점 참고 부탁드립니다.


 

동명이인이 있을 경우 문제가 되기 때문에 입금 후 입금 내역 캡쳐 혹은

입금 일시를 적어 회신 부탁드립니다.


 

현재 순차적으로 메일 답신 드리고 있어 안내가 늦어진 점 양해 부탁드립니다.


 

감사합니다. :)

**Comment by lionkang** [comment]
## 입금
- 하나은행으로 785,000원 입금완료 후 메일 전달

**Comment by lionkang** [comment]
## 배송예정
- 7월 30일 배송 예정임, 
- 동생으로 보내어야한다면 동생직장으로 바로 가도록 해야함

**Comment by lionkang** [comment]
동생집으로 배송예정, 완제품

**Comment by lionkang** [comment]
## 상태
- 헤드레스트 배송 완료, 2020년 7월 31일 
  - CJ택배, 632769008933

**Comment by lionkang** [comment]
8월 6일(목) 배송완료!

**Comment by lionkang** [comment]
### 2차판매진행
- 9월 23일(수) ~ 10월 14일(수) 까지 접수
- 1인당 2개 구매가능
- 비용
  - 에어론체어 : 673,000원
  - 헤드레스트 : 120,000원

**Comment by lionkang** [comment]
안녕하세요 가림 Herman Miller 입니다.
Herman Miller 와 네이버사 프로모션에 참여해 주셔서 감사합니다.

해당 제품은 고객님께서 직접 조립을 하셔야 하는 제품이며,
보내드리는 조립 방법을 보시고 문의사항이 있을 시
dongha@gareem.com 또는 전화 02-540-5433으로 연락 부탁드립니다.
제품 발송과 관련하여서는 별도로 배송 공지가 나갈 예정입니다.

[헤드레스트설치방법.jpg](https://drive.google.com/file/d/1zKVAXLRdO5gqeUqfFBmu0yCRKXwGxeG8/view?usp=sharing)
[New Aeron 조립방법.pdf](https://drive.google.com/file/d/1mRNyb4GSVOfZIN6eA9WEVVMcWWhaFFwa/view?usp=sharing)

추가적인 문의사항 있으시면 언제든지 연락주세요.
감사합니다. :)


GaReem T&D Co., Ltd.
Hermanmiller
Tel 822 540 5433
Fax 822 3468 5897

**Comment by devholic** [comment]
안녕하세요,

현재 CONNECT 게시글에 주문서 및 금액 정보를 사외로 유출하지 말아달라는 내용이 포함되어 있는데, 금액 관련된 내용은 블라인드 처리가 되어야 할 것 같습니다 😰
